### ISSUE TITLE
Multi Processing Array does not accept Large Electric Macerator from Extended Industrialization.

### ISSUE THREAD

**Issue by kalutro** [WhitePhant0m/Industrialization-Overdrive#2]
I assumed it would word as it is an electric multiblock, but I cannot put them in the slot. According the the ReadMe, it should work with this block.

**Comment by WhitePhant0m** [comment]
Large macerator is a macerator that works as 16 macerators, just use macerators in a Processing Array instead.
Large Macerator is also a bit more special type of a multiblock compared to the rest(same goes for the other "large" machines, like the large furnace. The MPA only takes "regular" multiblocks, like EBF, quarry, drilling rig, etc
